"""
Phase 2 — configuration generation.

Renders all configuration files from Jinja2 templates using the
collected issuer config and Phase 1 outputs.

Output files (written to .inji-deploy/{issuer_id}/):
  - certify-{id}.properties         Spring Boot config for Certify
  - helm-values-certify.yaml        Helm override values
  - helm-values-softhsm.yaml        SoftHSM Helm values
  - k8s-configmap.yaml              Kubernetes ConfigMap
  - k8s-secret-refs.yaml            External secret references
  - mimoto-issuer-patch.json        JSON entry to inject into mimoto config
  - db-init-values.yaml             postgres-init Helm values
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from jinja2 import Environment, BaseLoader, StrictUndefined
from rich.console import Console
from rich.panel import Panel

from inji_issuer_deploy.state import DeployState, save_state

console = Console()

OUTPUT_DIR_PREFIX = ".inji-deploy"


def _output_dir(issuer_id: str) -> Path:
    d = Path(OUTPUT_DIR_PREFIX) / issuer_id
    d.mkdir(parents=True, exist_ok=True)
    return d


def _render(template_str: str, context: dict) -> str:
    env = Environment(
        loader=BaseLoader(),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    return env.from_string(template_str).render(**context)


def _write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
    console.print(f"  [green]✓[/green] {path}")


# ── Templates ─────────────────────────────────────────────────

CERTIFY_PROPERTIES = """\
## ─────────────────────────────────────────────────────────────
## Inji Certify — {{ issuer_id }} issuer
## Generated by inji-issuer-deploy — do not edit manually
## ─────────────────────────────────────────────────────────────

spring.application.name=certify
server.port=8090
server.servlet.path=/v1/certify

## ── Discovery ───────────────────────────────────────────────
mosip.certify.domain.url=https://{{ base_domain }}
mosipbox.public.url=https://{{ base_domain }}
mosip.certify.authorization.url={{ idperu_issuer_uri }}
mosip.certify.discovery.issuer-id=https://{{ base_domain }}/v1/certify

## ── Authentication (IDPeru token validation) ─────────────────
mosip.certify.authn.issuer-uri={{ idperu_issuer_uri }}
mosip.certify.authn.jwk-set-uri={{ idperu_jwks_uri }}
mosip.certify.authn.filter-urls={ \
  '${server.servlet.path}/issuance/credential', \
  '${server.servlet.path}/issuance/vd11/credential', \
  '${server.servlet.path}/issuance/vd12/credential' \
}
mosip.certify.authn.allowed-audiences={ \
  'https://{{ base_domain }}/v1/certify/issuance/credential' \
}
mosip.certify.supported.jwt-proof-alg={'RS256','PS256','ES256','Ed25519'}

## ── Plugin mode ──────────────────────────────────────────────
mosip.certify.plugin-mode=DataProvider
mosip.certify.integration.scan-base-package=io.mosip.certify.restapidataprovider.integration
mosip.certify.integration.audit-plugin=LoggerAuditService
mosip.certify.integration.data-provider-plugin=RestApiDataProviderPlugin

## ── Data provider plugin ─────────────────────────────────────
mosip.certify.data-provider-plugin.restapi.base-url={{ data_api_base_url }}
certify.data-provider-plugin.restapi.document-number-key={{ document_number_claim }}
{% if filiation_claim %}
certify.data-provider-plugin.restapi.filiation-document-number-key={{ filiation_claim }}
{% endif %}
mosip.certify.data-provider-plugin.restapi.scope-endpoint-mapping={ \
{% for m in scope_mappings %}
  '{{ m.scope }}': '{{ m.profile }}'{% if not loop.last %}, \\{% endif %}

{% endfor %}
}
{% for m in scope_mappings %}
mosip.certify.data-provider-plugin.restapi.context-path.{{ m.scope | replace('-','_') }}={{ m.service }}
{% endfor %}
mosip.certify.data-provider-plugin.restapi.obtener-datos-path=/ObtenerDatos

## ── DID & signing ────────────────────────────────────────────
mosip.certify.data-provider-plugin.issuer.vc-sign-algo=Ed25519Signature2020
mosip.certify.data-provider-plugin.did-url=did:web:{{ base_domain | replace('.', ':') }}
mosip.certify.data-provider-plugin.credential-status.supported-purposes={'revocation'}

## ── Credential config display ────────────────────────────────
mosip.certify.credential-config.issuer.display={ \
  { \
    'name': '{{ issuer_name }}', \
    'locale': 'es' \
  } \
}
mosip.certify.credential-config.cryptographic-binding-methods-supported={ \
  'ldp_vc': {'did:jwk','did:web'}, \
  'vc+sd-jwt': {'did:jwk','did:web'} \
}
mosip.certify.credential-config.credential-signing-alg-values-supported={ \
  'Ed25519Signature2020': {'EdDSA'}, \
  'Ed25519Signature2018': {'EdDSA'} \
}
mosip.certify.credential-config.proof-types-supported={ \
  'jwt': {'proof_signing_alg_values_supported': {'RS256','PS256','ES256','Ed25519'}} \
}

## ── Security ─────────────────────────────────────────────────
mosip.certify.security.auth.post-urls={}
mosip.certify.security.auth.put-urls={}
mosip.certify.security.auth.get-urls={}
mosip.certify.security.ignore-csrf-urls=**/actuator/**,/favicon.ico,**/error, \\
  **/swagger-ui/**,**/v3/api-docs/**, \\
  **/issuance/**,**/credential-configurations/**,**/.well-known/**,**/credentials/**
mosip.certify.security.ignore-auth-urls=**/actuator/**,**/error,**/swagger-ui/**, \\
  **/v3/api-docs/**,**/issuance/**,**/rendering-template/**,**/system-info/**, \\
  **/credential-configurations/**,**/.well-known/**,**/credentials/**

## ── Key manager (SoftHSM) ────────────────────────────────────
mosip.kernel.keymanager.hsm.config-path=/home/mosip/keystore.p12
mosip.kernel.keymanager.hsm.keystore-type=PKCS12
mosip.kernel.keymanager.hsm.keystore-pass=${SOFTHSM_CERTIFY_SECURITY_PIN}
mosip.kernel.keymgr.hsm.health.check.enabled=true
mosip.kernel.keymgr.hsm.health.key.app-id=CERTIFY_SERVICE
mosip.kernel.keymgr.hsm.healthkey.ref-id=TRANSACTION_CACHE
mosip.kernel.keymgr.hsm.health.check.encrypt=true

## ── Database ─────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://{{ rds_host }}:{{ rds_port }}/{{ db_name }}?currentSchema=certify
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

## ── Cache ────────────────────────────────────────────────────
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
mosip.certify.cache.names=userinfo,vcissuance,templatecache,certificatedatacache
mosip.certify.cache.security.secretkey.reference-id=TRANSACTION_CACHE
mosip.certify.cache.security.algorithm-name=AES/GCM/NoPadding
mosip.certify.access-token-expire-seconds=86400

## ── Crypto ───────────────────────────────────────────────────
mosip.kernel.crypto.asymmetric-algorithm-name=RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING
mosip.kernel.crypto.symmetric-algorithm-name=AES/GCM/NoPadding
mosip.kernel.keygenerator.asymmetric-algorithm-name=RSA
mosip.kernel.keygenerator.symmetric-algorithm-name=AES
mosip.kernel.keygenerator.asymmetric-key-length=2048
mosip.kernel.keygenerator.symmetric-key-length=256
mosip.kernel.data-key-splitter=#KEY_SPLITTER#
mosip.kernel.crypto.gcm-tag-length=128
mosip.kernel.crypto.hash-algorithm-name=PBKDF2WithHmacSHA512
mosip.kernel.crypto.hash-symmetric-key-length=256
mosip.kernel.crypto.hash-iteration=100000
mosip.kernel.crypto.sign-algorithm-name=RS256
mosip.kernel.certificate.sign.algorithm=SHA256withRSA
mosip.keymanager.dao.enabled=false
crypto.PrependThumbprint.enable=true

## ── Actuator ─────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,info,prometheus
management.health.redis.enabled=true
"""

HELM_VALUES_CERTIFY = """\
# Helm override values for inji-certify — {{ issuer_id }}
# Generated by inji-issuer-deploy

replicaCount: 1

image:
  registry: docker.io
  repository: mosipid/inji-certify-with-plugins
  tag: "{{ chart_version }}"
  pullPolicy: Always

springServicePort: 8090

resources:
  limits:
    cpu: 500m
    memory: 2250Mi
  requests:
    cpu: 100m
    memory: 1500Mi

additionalResources:
  javaOpts: "-Xms1500M -Xmx1500M"

{% if provider == 'onprem' %}
istio:
  enabled: false

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/{{ cert_issuer_kind | lower }}: {{ cert_issuer_name }}
  hosts:
    - host: {{ base_domain }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: inji-{{ issuer_id }}-tls
      hosts:
        - {{ base_domain }}
{% else %}
istio:
  enabled: true
  hosts:
    - {{ base_domain }}
  uriMatches:
    - matchType: exact
      uri: /.well-known/openid-credential-issuer
      rewriteUri: /v1/certify/issuance/.well-known/openid-credential-issuer
      port: 80
    - matchType: prefix
      uri: /
      port: 80
{% endif %}

volumes:
  - name: certify-props
    configMap:
      name: certify-{{ issuer_id }}-props
      items:
        - key: certify-{{ issuer_id }}.properties
          path: certify-{{ issuer_id }}.properties

volumeMounts:
  - name: certify-props
    mountPath: /config
    readOnly: true

extraEnv:
  - name: SPRING_CONFIG_LOCATION
    value: "file:///config/certify-{{ issuer_id }}.properties"
  - name: MOSIP_CERTIFY_INTEGRATION_SCAN_BASE_PACKAGE
    value: "io.mosip.certify.restapidataprovider.integration"

extraEnvVarsCM:
  - inji-{{ issuer_id }}-config
  - softhsm-certify-{{ issuer_id }}-share

extraEnvVars: |
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: inji-{{ issuer_id }}-db-secret
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: inji-{{ issuer_id }}-db-secret
        key: password
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: inji-{{ issuer_id }}-redis-secret
        key: redis-password
        optional: true

serviceAccount:
  create: true
  name: inji-{{ issuer_id }}-sa
{% if pod_identity_role_arn and pod_identity_role_arn.startswith('arn:') %}
  annotations:
    eks.amazonaws.com/role-arn: "{{ pod_identity_role_arn }}"
{% endif %}

metrics:
  enabled: true
  serviceMonitor:
    enabled: {{ 'false' if provider == 'onprem' else 'true' }}
    interval: 10s
"""

HELM_VALUES_SOFTHSM = """\
# SoftHSM values for inji-certify {{ issuer_id }}
# Generated by inji-issuer-deploy

security:
  pin: "${SOFTHSM_CERTIFY_{{ issuer_id | upper }}_SECURITY_PIN}"
"""

K8S_CONFIGMAP = """\
apiVersion: v1
kind: ConfigMap
metadata:
  name: inji-{{ issuer_id }}-config
  namespace: inji-{{ issuer_id }}
  labels:
    app: inji-certify
    issuer: {{ issuer_id }}
    managed-by: inji-issuer-deploy
data:
  active_profile_env: "default,{{ issuer_id }}"
  mosip_certify_domain_url: "https://{{ base_domain }}"
  rds_host: "{{ rds_host }}"
  rds_port: "{{ rds_port }}"
  db_name: "{{ db_name }}"
  idperu_issuer_uri: "{{ idperu_issuer_uri }}"
  idperu_jwks_uri: "{{ idperu_jwks_uri }}"
"""

MIMOTO_ISSUER_ENTRY = """\
{
  "issuer_id": "{{ issuer_id }}",
  "credential_issuer": "{{ issuer_id }}",
  "protocol": "OpenId4VCI",
  "display": [
    {
      "name": "{{ issuer_name }}",
      "title": "{{ issuer_name }}",
      "description": "{{ issuer_description }}",
      "logo": {
        "url": "{{ issuer_logo_url }}",
        "alt_text": "{{ issuer_id }}-logo"
      },
      "language": "es"
    }
  ],
  "client_id": "inji-wallet-{{ issuer_id }}",
  "redirect_uri": "io.mosip.residentapp.inji://oauthredirect",
  "token_endpoint": "https://{{ mimoto_domain }}/v1/mimoto/get-token/{{ issuer_id }}",
  "authorization_audience": "{{ idperu_issuer_uri }}/oauth/v2/token",
  "proxy_token_endpoint": "{{ idperu_issuer_uri }}/oauth/v2/token",
  "client_alias": "inji-wallet-{{ issuer_id }}-client",
  "qr_code_type": "EmbeddedVC",
  "enabled": "true",
  "wellknown_endpoint": "https://{{ base_domain }}/.well-known/openid-credential-issuer",
  "credential_issuer_host": "https://{{ base_domain }}/v1/certify"
}
"""

DB_INIT_VALUES = """\
# postgres-init Helm values for inji-{{ issuer_id }}
# Generated by inji-issuer-deploy
databases:
  {{ db_name }}:
    enabled: true
    host: "{{ rds_host }}"
    port: {{ rds_port }}
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/inji-certify.git
    branch: v{{ chart_version }}
"""


# ── main ─────────────────────────────────────────────────────

def run(state: DeployState, dry_run: bool = False) -> None:
    console.print(Panel(
        "[bold]Phase 2 — Configuration generation[/bold]",
        border_style="cyan",
    ))

    cfg = state.issuer
    infra = state.phase("infra").outputs
    out_dir = _output_dir(cfg.issuer_id)

    # Derive mimoto domain from S3 bucket name or use a default
    mimoto_domain = f"mimoto.{'.'.join(cfg.base_domain.split('.')[-2:])}"

    raw_pc = getattr(state, "provider_cfg", None) or {}
    provider = raw_pc.get("provider", "onprem") if isinstance(raw_pc, dict) else getattr(raw_pc, "provider", "onprem")
    cert_issuer_kind = raw_pc.get("onprem_cert_issuer_kind", "ClusterIssuer") if isinstance(raw_pc, dict) else getattr(raw_pc, "onprem_cert_issuer_kind", "ClusterIssuer")
    cert_issuer_name = raw_pc.get("onprem_cert_issuer_name", "letsencrypt-prod") if isinstance(raw_pc, dict) else getattr(raw_pc, "onprem_cert_issuer_name", "letsencrypt-prod")

    context = {
        "issuer_id":             cfg.issuer_id,
        "issuer_name":           cfg.issuer_name,
        "issuer_description":    cfg.issuer_description,
        "issuer_logo_url":       cfg.issuer_logo_url,
        "base_domain":           cfg.base_domain,
        "rds_host":              cfg.rds_host,
        "rds_port":              cfg.rds_port,
        "db_name":               infra.get("db_name", f"inji_{cfg.issuer_id}"),
        "idperu_jwks_uri":       cfg.idperu_jwks_uri,
        "idperu_issuer_uri":     cfg.idperu_issuer_uri,
        "document_number_claim": cfg.document_number_claim,
        "filiation_claim":       cfg.filiation_claim,
        "data_api_base_url":     cfg.data_api_base_url,
        "data_api_auth_type":    cfg.data_api_auth_type,
        "scope_mappings":        cfg.scope_mappings,
        "chart_version":         cfg.chart_version,
        "softhsm_chart_version": cfg.softhsm_chart_version,
        "pod_identity_role_arn": infra.get("pod_identity_role_arn", ""),
        "mimoto_domain":         mimoto_domain,
        "namespace":             f"inji-{cfg.issuer_id}",
        "provider":              provider,
        "cert_issuer_kind":      cert_issuer_kind,
        "cert_issuer_name":      cert_issuer_name,
    }

    if dry_run:
        console.print(f"[yellow]DRY RUN — files would be written to {out_dir}/[/yellow]")
        for name in [
            f"certify-{cfg.issuer_id}.properties",
            "helm-values-certify.yaml",
            "helm-values-softhsm.yaml",
            "k8s-configmap.yaml",
            "mimoto-issuer-patch.json",
            "db-init-values.yaml",
        ]:
            console.print(f"  [dim]→ {out_dir / name}[/dim]")
        return

    state.mark_started("config_gen")
    outputs: dict = {}

    try:
        files = {
            f"certify-{cfg.issuer_id}.properties": CERTIFY_PROPERTIES,
            "helm-values-certify.yaml":             HELM_VALUES_CERTIFY,
            "helm-values-softhsm.yaml":             HELM_VALUES_SOFTHSM,
            "k8s-configmap.yaml":                   K8S_CONFIGMAP,
            "mimoto-issuer-patch.json":             MIMOTO_ISSUER_ENTRY,
            "db-init-values.yaml":                  DB_INIT_VALUES,
        }
        for filename, template in files.items():
            content = _render(template, context)
            path = out_dir / filename
            if not dry_run:
                _write(path, content)
            outputs[filename] = str(path)

    except Exception as exc:
        state.mark_failed("config_gen", str(exc))
        save_state(state)
        raise

    state.mark_done("config_gen", outputs)
    save_state(state)
    console.print(
        f"\n[green]Phase 2 complete — {len(outputs)} files written to "
        f"{out_dir}/[/green]"
    )
